Miny.Web/Models/ViewModels/CreateItemViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MINY.Web.Models.ViewModels
{
    public class CreateItemViewModel
    {
        [Required]
        public int WallId { get; set; }
        [Required]
        public int AuthorId { get; set; }
        public string Note { get; set; }
        public string Url { get; set; }
        public string PicturePath { get; set; }
        public string VideoPath { get; set; }
        public int NbCol { get; set; }

        public bool IsEmpty
        {
            get
            {
                return Note == null && Url == null && PicturePath == null && VideoPath == null ? true : false;
            }
        }
    }
}

Miny.Web/Models/ViewModels/WallViewModel.cs
using MINY.Web.Datas;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MINY.Web.Models.ViewModels
{
    public class WallViewModel
    {
        public vWallDetail WallDetail { get; set; }
        public IEnumerable<vItem> Items { get; set; }

        public IEnumerable<vItem> SortedItems
        {
            get { return Items.Reverse(); }
        }
    }
}

Miny.Web/Controllers/MinyController.cs
using MINY.Web.Datas;
using MINY.Web.Models.ViewModels;
using MINY.Web.Services;
using System;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace MINY.Web.Controllers
{
    public class MinyController : Controller
    {
        private IDataReader _dataReader = new DataReader();
        private IDataRepository _repository = new DataRepository();
        private IMinyServices _services = new MinyServices(); 

        public ActionResult Wall(int id)
        {
            return View( new WallViewModel
                {
                    WallDetail = _dataReader.GetWallDetailById(id),
                    Items = _dataReader.GetWallItemsById(id)
                }
            );
        }

        [HttpPost]
        public ActionResult CreateItem( CreateItemViewModel model )
        {
            if(Request.IsAjaxRequest())
            {
                if(!model.IsEmpty)
                {
                    return Json( _services.BuildItemToPrepend( _dataReader.GetItemById( _repository.CreateItem( model ) ) ) );
                }
                //TODO return Json EmptyModelError
            }
            
            return _repository.CreateItem( model ) != 0 ?
                (ActionResult)RedirectToAction( "Wall" ) : View( "_createItemError" ); // TODO Handle error
        }

        [HttpGet]
        public ActionResult DeleteItem( int id )
        {
            if(Request.IsAjaxRequest())
            {
                return _repository.DeleteItem( id ) ?
                    Json( id, JsonRequestBehavior.AllowGet ) : Json( 0, JsonRequestBehavior.AllowGet );
            }

            return _repository.DeleteItem( id ) ?
                    (ActionResult)RedirectToAction( "Wall" ) : View( "_deleteItemConfirmation" ); // TODO handle Confirmation
        }
    }
}

Miny.Web/Views/Home/Index.cshtml
@model MINY.Web.Models.HomeViewModel

@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Home</h2>

<div id="result"></div>

@using(Ajax.BeginForm("Create", "Home", new AjaxOptions { UpdateTargetId = "result", HttpMethod = "post" } ))
{ 
    <fieldset>
        @Html.LabelFor(x => x.AreaName)
        @Html.EditorFor(x => x.AreaName)
        <input type="submit" value="validate" />
    </fieldset>
}

Miny.Web/Views/Miny/TestRegex.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Works bitch</title>
</head>
<body>
    <div>
        
    </div>
</body>
</html>

Miny.Web/Views/Miny/Wall.cshtml
@model MINY.Web.Models.ViewModels.WallViewModel

@{
    ViewBag.Title = "Wall";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.WallDetail.Name</h2>
@{
    MINY.Web.Models.ViewModels.CreateItemViewModel c = new MINY.Web.Models.ViewModels.CreateItemViewModel();
    c.WallId = Model.WallDetail.WallId;
    c.AuthorId = 1;
}

<section>
    @Html.Partial( "_createItem", c )
    @Html.Partial( "_wallItems", Model.SortedItems )
</section>

@Scripts.Render("~/bundles/jquerymasonry")
@Scripts.Render("~/bundles/bootstrapjs")
@Scripts.Render("~/bundles/minyjs")

Miny.Web/Views/Miny/_createItem.cshtml
@model MINY.Web.Models.ViewModels.CreateItemViewModel

@{
    AjaxOptions options = new AjaxOptions { OnSuccess = "ItemAdded" };
}

<div id="waitingForCreation"></div>
<div id="createItemForm" class="">
    @using(Ajax.BeginForm( "CreateItem", "Miny", options ))
    {
        <ul>
            <li id="addNote" class="addElement">
                @Html.Label( "Note" )
               <input id="Note" class="input-block-level" name="Note" placeHolder="Ajoutez une note..." type="text" value="" />
            </li>
    
            <li id="addUrl" class="addElement">
                @Html.Label( "Lien" )
                <input id="Url" class="input-block-level" name="Url" placeHolder="Ajoutez un lien..." type="text" value="" />
           
            </li>

            <li id="addPicture" class="addElement">
                @Html.Label( "Image" )
                <input id="PicturePath" class="input-block-level" name="PicturePath" placeHolder="Ajoutez une image..." type="text" value="" />
            </li>

            <li id="addVideo" class="addElement">
                @Html.Label( "Vidéo" )
                <input id="VideoPath" class="input-block-level" name="VideoPath" placeHolder="Ajoutez une vidéo..." type="text" value="" />
            </li>

            <li id="NbCol" class="addElement">
                @Html.Label( "Nombre de colonnes" )
                <label class="radio inline">
                <input type="radio" name="NbCol" id="optionsRadios1" value="1" checked>
                    1
                </label>
                <label class="radio inline">
                <input type="radio" name="NbCol" id="optionsRadios2" value="2">
                    2
                </label>
                <label class="radio inline">
                <input type="radio" name="NbCol" id="optionsRadios3" value="3">
                    3
                </label>           
            </li>
        </ul>
    
        @Html.HiddenFor( x => x.WallId );
        @Html.HiddenFor( x => x.AuthorId ); 
        <input id="" class="btn btn-large btn-block btn-info" type="submit" value="Soumettre" />
    }
</div>

@Scripts.Render( "~/bundles/watch" );

Miny.Web/Views/Miny/_wallItems.cshtml
@model IEnumerable<MINY.Web.Datas.vItem>

<div id="container">
    @foreach(var v in Model)
    { 
        string NbCol = "col" + v.NbCol; 
        <div id="item-@v.ItemId" class="item col @NbCol">
            @if( v.Note != null ) { <div class="note element"><p>@v.Note</p></div> }
                
            @if( v.PicturePath != null ) 
            { 
                <div class="picture element">
                    <img src="@v.PicturePath" alt="Sorry, picture not found..." />
                </div> 
            }

            @if( v.VideoPath != null  )
            { 
                string videoHeight = "videoHeight" + v.NbCol;
                <div class="video element">
                    <iframe class="@videoHeight" src="@v.VideoPath"></iframe>
                </div>
            }

            @if( v.Url != null  ) 
            { 
                <div class="url element">
                    <a href="@v.Url">@v.Url</a>
                </div> 
            }

            @Ajax.ActionLink( 
                "Delete this item", 
                "DeleteItem", 
                "Miny", 
                new { id = v.ItemId }, 
                new AjaxOptions 
                    { OnSuccess = "ItemDeleted", Confirm = "Delete permanently ?" } 
                )
        </div>
    }
    <div class="item col col1">
        Curabitur ullamcorper 
        egestas sapien, eu volutpat purus blandit volutpat. Nullam at leo rhoncus tortor convallis 
        hendrerit. Ut iaculis placerat dolor.
    </div>
    <div class="item col col1">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent pharetra ultrices 
        molestie. Curabitur rutrum iaculis pellentesque. Nulla convallis faucibus hendrerit. 
        Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis 
        egestas. Nam suscipit aliquam ligula, sed elementum ligula lacinia sagittis. 
        Proin eu elit odio. Nullam mattis tempus hendrerit. Pellentesque habitant morbi 
        tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur ullamcorper 
        egestas sapien, eu volutpat purus blandit volutpat. Nullam at leo rhoncus tortor convallis 
        hendrerit. Ut iaculis placerat dolor. 
    </div>
    <div class="item col col1">
        Nullam mattis tempus hendrerit.
    </div>
    <div class="item col col1">
        Nullam mattis tempus hendrerit. Pellentesque habitant morbi 
        tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur ullamcorper 
        egestas sapien, eu volutpat purus blandit volutpat. Nullam at leo rhoncus tortor convallis 
        hendrerit. Ut iaculis placerat dolor. 
    </div>
    <div class="item col col1">
        Nullam at leo rhoncus tortor convallis 
        hendrerit. Ut iaculis placerat dolor.
    </div>
    <div class="item col col1">
        <img src="~/Content/themes/base/images/slide-1.jpg" />
    </div>
    <div class="item col col1">
        Nam suscipit aliquam ligula, sed elementum ligula lacinia sagittis. 
        Proin eu elit odio.
    </div>
    <div class="item col col1">
        Nullam mattis tempus hendrerit. Pellentesque habitant morbi 
        tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur ullamcorper 
        egestas sapien, eu volutpat purus blandit volutpat. Nullam at leo rhoncus tortor convallis 
        hendrerit. Ut iaculis placerat dolor. 
    </div>
    <div class="item col col1">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent pharetra ultrices 
        molestie. Curabitur rutrum iaculis pellentesque. Nulla convallis faucibus hendrerit. 
        Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis 
        egestas. Nam suscipit aliquam ligula, sed elementum ligula lacinia sagittis. 
        Proin eu elit odio. Nullam mattis tempus hendrerit. Pellentesque habitant morbi 
        tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur ullamcorper 
        egestas sapien, eu volutpat purus blandit volutpat. Nullam at leo rhoncus tortor convallis 
        hendrerit. Ut iaculis placerat dolor. 
    </div>
    <div class="item col col1">
        Nullam at leo rhoncus tortor convallis 
        hendrerit. Ut iaculis placerat dolor.
    </div>
    <div class="item col col1">
        <img src="~/Content/themes/base/images/slide-2.jpg" />
    </div>
    <div class="item col col1">
        Nullam mattis tempus hendrerit. Pellentesque habitant morbi 
        tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur ullamcorper 
        egestas sapien, eu volutpat purus blandit volutpat. Nullam at leo rhoncus tortor convallis 
        hendrerit. Ut iaculis placerat dolor. 
    </div>
    <div class="item col col1">
        Nullam mattis tempus hendrerit.
    </div>
    <div class="item col col1">
        Nullam mattis tempus hendrerit. Pellentesque habitant morbi 
        tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur ullamcorper 
        egestas sapien, eu volutpat purus blandit volutpat. Nullam at leo rhoncus tortor convallis 
        hendrerit. Ut iaculis placerat dolor. 
    </div>
    <div class="item col col1">
        Nullam mattis tempus hendrerit. Pellentesque habitant morbi 
        tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur ullamcorper 
        egestas sapien, eu volutpat purus blandit volutpat. Nullam at leo rhoncus tortor convallis 
        hendrerit. Ut iaculis placerat dolor. 
    </div>
    <div class="item col col1">
        Nullam mattis tempus hendrerit.
    </div>
    <div class="item col col1">
        <img src="~/Content/themes/base/images/slide-3.jpg" />
    </div>
    <div class="item col col1">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent pharetra ultrices 
        molestie. Curabitur rutrum iaculis pellentesque. Nulla convallis faucibus hendrerit. 
        Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis 
        egestas. Nam suscipit aliquam ligula, sed elementum ligula lacinia sagittis. 
        Proin eu elit odio. Nullam mattis tempus hendrerit. Pellentesque habitant morbi 
        tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur ullamcorper 
        egestas sapien, eu volutpat purus blandit volutpat. Nullam at leo rhoncus tortor convallis 
        hendrerit. Ut iaculis placerat dolor. 
    </div>
    <div class="item col col1">
        Nullam mattis tempus hendrerit. Pellentesque habitant morbi 
        tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur ullamcorper 
        egestas sapien, eu volutpat purus blandit volutpat. Nullam at leo rhoncus tortor convallis 
        hendrerit. Ut iaculis placerat dolor. 
    </div>
    <div class="item col col1">
        Nullam mattis tempus hendrerit.
    </div>
    <div class="item col col1">
        Nullam mattis tempus hendrerit. Pellentesque habitant morbi 
        tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur ullamcorper 
        egestas sapien, eu volutpat purus blandit volutpat. Nullam at leo rhoncus tortor convallis 
        hendrerit. Ut iaculis placerat dolor. 
    </div>
     <div class="item col col1">
        Nullam at leo rhoncus tortor convallis 
        hendrerit. Ut iaculis placerat dolor.
    </div>
    <div class="item col col1">
        Nullam mattis tempus hendrerit. Pellentesque habitant morbi 
        tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur ullamcorper 
        egestas sapien, eu volutpat purus blandit volutpat. Nullam at leo rhoncus tortor convallis 
        hendrerit. Ut iaculis placerat dolor. 
    </div>
    <div class="item col col1">
        Nullam mattis tempus hendrerit.
    </div>
    <div class="item col col1">
        Nullam mattis tempus hendrerit.
    </div>
    <div class="item col col1">
        Nullam mattis tempus hendrerit. Pellentesque habitant morbi 
        tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur ullamcorper 
        egestas sapien, eu volutpat purus blandit volutpat. Nullam at leo rhoncus tortor convallis 
        hendrerit. Ut iaculis placerat dolor. 
    </div>
     <div class="item col col1">
        Nullam at leo rhoncus tortor convallis 
        hendrerit. Ut iaculis placerat dolor.
    </div>
</div>

Miny.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/Bootstrapcss")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
</head>
<body>
    @RenderBody()
    @RenderSection("scripts", required: false)    
</body>
</html>